### ISSUE TITLE
Token counting for Audio input

### ISSUE THREAD

**Issue by aalhayali** [google-gemini/cookbook#161]
### Description of the feature request:

It would be great to know a close estimate of how many tokens it costs per minute of audio. In this [guide](https://github.com/google-gemini/cookbook/blob/main/quickstarts/Counting_Tokens.ipynb), it mentions "Audio and video are each converted to tokens at a fixed rate of tokens per minute." Using the audio example you used in the guide as a reference point, for ~44 minutes of audio, it would cost ~1,899 tokens/minute of audio (83552/44). Is my understanding correct? Also, would the number of tokens change based on the audio input type (eg. wav vs mp3)?

### What problem are you trying to solve with this feature?

Estimating the count of tokens for audio input.

**Comment by SivaMalasani** [comment]
**Token count depends upon the length of the audio rather than the size or type of the audio input**
I investigated how audio format and file size affect the number of tokens generated from audio. I used audio clips of the same length (3.07 minutes) in various formats (mp3, wav, flac, aac and m4a). Interestingly, the token count did not depend on the format or file size of the audio. Instead, it solely relied on the audio's duration. In other words, clips with the same length resulted in the same number of tokens, regardless of format or file size.
Please find the [gist](https://colab.sandbox.google.com/gist/SivaMalasani/1ba936c13636acd9bacff63dd45ac8da/tocken-counting.ipynb)

**Comment by markmcd** [comment]
I think this is answered now. Feel free to open another issue if you think there's more we can do.
