### ISSUE TITLE
Option to specify a default language for the conversation in Multimodal Live API for Gemini 2

### ISSUE THREAD

**Issue by notnotrishi** [google-gemini/cookbook#381]
### Description of the feature request:

I noticed the API sometimes switches to German voice even though I speak in English; would be nice to force the conversation to a  certain default language. I have tried to use system instruction as a workaround but it doesn't solve the problem 100% of the time.

I understand this might be a challenge for multi language conversations but I guess a 'default' could force it to respond in specified language when it's confused?

**Comment by Giom-V** [comment]
It should be already defaulting to English unless asked otherwise. I'd say try using system instructions to give it clearer instructions to always speak in English.
That said, thanks for the feedback that I'll route to the right team. Keep in mind that it is still an experimental model so still far from perfect.
